### PR TITLE
Notebook fixes

### LINKED ISSUE #7: Update notebooks to use PyTensor
@LifeWorks noticed that the notebooks in emll are still importing the old theano library.

### PR DESCRIPTION
**Pull request by mcnaughtonadm**
This PR will fix #7 .

Still in DRAFT.

Need to update the following Notebooks:
- [x] contador.ipynb
- [x] hackett.ipynb
- [x] run_hacket_inference.py
- [x] wu2004.ipynb

### CODE REVIEW

**Comment by mcnaughtonadm** [comment]
I'm biting the bullet a little, and updating to much more recent `pymc` and `pytensor` implementations. I am trying hard to replicate the outputs as much as possible, but processes have changed since the initial release of `emll` and there are quite a few deprecations and alternative data formats I am working through.

**Comment by mcnaughtonadm** [comment]
Re-running the `run_hackett_inference.py` script to be in compliance with new `PyMC`/`PyTensor` format, once finished `hackett.ipynb` can be fixed and merge can be made.

**Comment by mcnaughtonadm** [comment]
This is ready to review @djinnome . You should hopefully be able to run all the notebooks now with PyTensor and current PyMC if you install the package. The new adherence to `ArViz` inference data structures has been followed and the results are _mostly_ the same as before. We may need to alter the way we do data analysis in the future to adhere to the new format. But this is just for the notebooks. The actualy `emll` code is fine.

**Review by djinnome — APPROVED** [review]
Modulo the FCC plot in Hackett looks a little off.  Create a new issue for that specific problem.

**Pull request merged**
